export const swaggerDocument = {
  openapi: '3.0.3',
  info: { title: 'LMS Platform API (MySQL)', version: '2.0.0', description: 'Production LMS REST API — Express + TypeScript + Prisma + MySQL + JWT' },
  servers: [{ url: 'http://localhost:5000/api' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    schemas: {
      Register: { type: 'object', required: ['name', 'email', 'password'], properties: { name: { type: 'string' }, email: { type: 'string' }, password: { type: 'string' }, role: { type: 'string', enum: ['STUDENT', 'MENTOR'] } } },
      Login: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string' }, password: { type: 'string' } } },
      Course: { type: 'object', required: ['title', 'description', 'category'], properties: { title: { type: 'string' }, subtitle: { type: 'string' }, description: { type: 'string' }, category: { type: 'string' }, price: { type: 'number' }, level: { type: 'string' }, status: { type: 'string' } } },
      Quiz: { type: 'object', required: ['courseId', 'title', 'questions'], properties: { courseId: { type: 'string' }, moduleId: { type: 'string' }, title: { type: 'string' }, passingPercentage: { type: 'number' }, questions: { type: 'array', items: { type: 'object' } } } },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/auth/register': { post: { tags: ['Auth'], summary: 'Register', requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Register' } } } }, responses: { '201': { description: 'Created' } } } },
    '/auth/login': { post: { tags: ['Auth'], summary: 'Login', requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Login' } } } }, responses: { '200': { description: 'OK' } } } },
    '/auth/refresh': { post: { tags: ['Auth'], summary: 'Refresh tokens', responses: { '200': { description: 'OK' } } } },
    '/auth/logout': { post: { tags: ['Auth'], summary: 'Logout', responses: { '200': { description: 'OK' } } } },
    '/auth/me': { get: { tags: ['Auth'], summary: 'Current user', responses: { '200': { description: 'OK' } } } },
    '/users': { get: { tags: ['Users'], summary: 'List users (admin)', responses: { '200': { description: 'OK' } } } },
    '/users/{id}': { get: { tags: ['Users'], summary: 'Get user', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/courses': {
      get: { tags: ['Courses'], summary: 'List courses (paginated, search/filter/sort)', parameters: [{ name: 'page', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }, { name: 'search', in: 'query', schema: { type: 'string' } }, { name: 'level', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } },
      post: { tags: ['Courses'], summary: 'Create course (mentor)', requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Course' } } } }, responses: { '201': { description: 'Created' } } },
    },
    '/courses/{id}': { get: { tags: ['Courses'], summary: 'Get course', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } }, put: { tags: ['Courses'], summary: 'Update course', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } }, delete: { tags: ['Courses'], summary: 'Delete course', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/courses/{courseId}/modules': { get: { tags: ['Modules'], summary: 'List modules', parameters: [{ name: 'courseId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } }, post: { tags: ['Modules'], summary: 'Create module', parameters: [{ name: 'courseId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '201': { description: 'Created' } } } },
    '/modules/{moduleId}/lessons': { get: { tags: ['Lessons'], summary: 'List lessons', parameters: [{ name: 'moduleId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } }, post: { tags: ['Lessons'], summary: 'Create lesson', parameters: [{ name: 'moduleId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '201': { description: 'Created' } } } },
    '/courses/{courseId}/enroll': { post: { tags: ['Enrollment'], summary: 'Enroll in course', parameters: [{ name: 'courseId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '201': { description: 'Enrolled' } } } },
    '/enrollments/my-courses': { get: { tags: ['Enrollment'], summary: 'My enrollments', responses: { '200': { description: 'OK' } } } },
    '/lessons/{lessonId}/complete': { post: { tags: ['Progress'], summary: 'Mark lesson complete', parameters: [{ name: 'lessonId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/courses/{courseId}/progress': { get: { tags: ['Progress'], summary: 'Course progress', parameters: [{ name: 'courseId', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/quizzes/{id}': { get: { tags: ['Quizzes'], summary: 'Get quiz (answers hidden for students)', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/quizzes/{id}/submit': { post: { tags: ['Quizzes'], summary: 'Submit quiz', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '201': { description: 'Graded' } } } },
    '/certificates/{id}': { get: { tags: ['Certificates'], summary: 'Get certificate', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
    '/users/me/certificates': { get: { tags: ['Certificates'], summary: 'My certificates', responses: { '200': { description: 'OK' } } } },
    '/certificates/verify/{certificateNumber}': { get: { tags: ['Certificates'], summary: 'Verify certificate', parameters: [{ name: 'certificateNumber', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } } },
  },
} as const;
